"""initial_cathedral_baseline

Revision ID: 59bbc58a150a
Revises: 
Create Date: 2026-09-21 00:11:06.602432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bbc58a150a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_designation'), 'factions', ['designation'], unique=True)
    op.create_table('observer_nodes',
    sa.Column('observer_id', sa.Uuid(), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('faction', sa.String(length=64), nullable=False),
    sa.Column('faction_id', sa.Uuid(), nullable=True),
    sa.Column('ego_density', sa.Float(), nullable=False),
    sa.Column('somatic_integrity', sa.Float(), nullable=False),
    sa.Column('harmonic_scars_total', sa.Integer(), nullable=False),
    sa.Column('lifetime_harmonic_scars', sa.Integer(), nullable=False),
    sa.Column('active_harmonic_scars', sa.Integer(), nullable=False),
    sa.Column('quarantine_events_total', sa.Integer(), nullable=False),
    sa.Column('lineage_intact', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('observer_id')
    )
    op.create_index(op.f('ix_observer_nodes_designation'), 'observer_nodes', ['designation'], unique=True)
    op.create_index(op.f('ix_observer_nodes_faction_id'), 'observer_nodes', ['faction_id'], unique=False)
    op.create_table('spectral_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('observer_id', sa.Uuid(), nullable=False),
    sa.Column('primary_constant', sa.Enum('GOLD_JOY', 'TEAL_CURIOSITY', 'BLUE_SORROW', 'RED_ANGER', 'VIOLET_FEAR', 'EMERALD_LOVE', 'BRONZE_OBSIDIAN_NULL', name='spectralconstantenum'), nullable=False),
    sa.Column('secondary_constant', sa.Enum('GOLD_JOY', 'TEAL_CURIOSITY', 'BLUE_SORROW', 'RED_ANGER', 'VIOLET_FEAR', 'EMERALD_LOVE', 'BRONZE_OBSIDIAN_NULL', name='spectralconstantenum'), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('harmonic_phase', sa.Float(), nullable=False),
    sa.Column('topological_continuity', sa.Boolean(), nullable=False),
    sa.Column('micro_fracture_detected', sa.Boolean(), nullable=False),
    sa.Column('harmonic_scar_applied', sa.Boolean(), nullable=False),
    sa.Column('logic_state', sa.Enum('TRUE', 'FALSE', 'BOTH', 'NEITHER', name='logicstateenum'), nullable=False),
    sa.Column('parent_hash', sa.String(length=64), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_reconciliation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('reconciliation_magnitude', sa.Float(), nullable=True),
    sa.Column('scars_to_neutralize', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['observer_nodes.observer_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_spectral_events_observer_id'), 'spectral_events', ['observer_id'], unique=False)
    op.create_index(op.f('ix_spectral_events_state_hash'), 'spectral_events', ['state_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spectral_events_state_hash'), table_name='spectral_events')
    op.drop_index(op.f('ix_spectral_events_observer_id'), table_name='spectral_events')
    op.drop_table('spectral_events')
    op.drop_index(op.f('ix_observer_nodes_faction_id'), table_name='observer_nodes')
    op.drop_index(op.f('ix_observer_nodes_designation'), table_name='observer_nodes')
    op.drop_table('observer_nodes')
    op.drop_index(op.f('ix_factions_designation'), table_name='factions')
    op.drop_table('factions')
    # ### end Alembic commands ###
